version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8002:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis:/data
  nats:
    image: nats:latest
    command: [
      "-js",
      "-m", "8222",
      "-sd", "/data"
    ]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
  nui:
    image: ghcr.io/nats-nui/nui:latest
    ports:
      - "31311:31311"
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats

volumes:
  rabbitmq:
  redis:
  nats: